
const MENSAGENS = [
  // Produtividade e Sucesso
  '🌅 Ótimo dia para ser produtiva!',
  '💪 Você consegue conquistar tudo hoje!',
  '✨ Que seu dia seja tão brilhante quanto você!',
  '🎯 Vamos alcançar nossos objetivos!',
  '☀️ Um novo dia, novas oportunidades!',
  '🚀 Hoje é o dia para fazer acontecer!',
  '⭐ Você é capaz de coisas incríveis!',
  '💎 Cada dia é uma chance de brilhar!',
  '🔥 Bora colocar as mãos na massa!',
  '🌟 Seu potencial é infinito!',
  '🎪 Hoje vamos fazer história!',
  '💫 Acredite em seu trabalho!',
  '🏆 Você é uma vencedora!',
  '🌈 Cada desafio é uma oportunidade!',
  '⚡ Sua energia é contagiante!',
  '🎨 Crie sua própria história de sucesso!',
  '🌸 Hoje é perfeito para começar!',
  '🎭 Seja a protagonista da sua vida!',
  '💝 Você merece tudo de bom!',
  '🌺 Floresça no seu próprio tempo!',
 
  // Força e Coragem
  '💪 Você é mais forte do que pensa!',
  '🦁 Tenha coragem de ser você mesma!',
  '⚔️ Enfrente seus medos com confiança!',
  '🛡️ Você consegue superar qualquer obstáculo!',
  '🏔️ Escale montanhas! Você consegue!',
  '🌊 Surfe nas ondas da vida com segurança!',
  '🔐 Sua força vem de dentro!',
  '💥 Exploda em potencial!',
  '🎯 Mire alto e acerte!',
  '🚂 Siga em frente, sempre em frente!',
  '🌳 Tenha raízes fortes e crescimento livre!',
  '⚙️ Engrenagens da vitória em movimento!',
  '🎪 Circo da vida: você é a melhor atriz!',
  '🏅 Você é merecedora de ouro!',
  '🚁 Suba mais alto que suas limitações!',
 
  // Motivação Pessoal
  '🌟 Você é incrível do jeito que é!',
  '✨ Sua essência brilha naturalmente!',
  '💖 Ame-se primeiro, sempre!',
  '🎁 Você é um presente para o mundo!',
  '👑 Você é realeza!',
  '🦋 Transforme-se em algo melhor!',
  '🌻 Seja a luz do seu próprio caminho!',
  '🎸 Toque a música do seu coração!',
  '🌙 Mesmo nas noites escuras, brilhe!',
  '☄️ Seja uma estrela cadente de sucesso!',
  '🎨 Pinte seu destino com cores vibrantes!',
  '🌴 Relaxe, mas não desista dos sonhos!',
  '🎭 Você é uma obra de arte!',
  '🏖️ Encontre paz na sua jornada!',
  '🎪 Divirta-se enquanto conquista!',
  '🌺 Você é uma flor única!',
  '🦚 Exiba sua beleza interior!',
  '💎 Você é preciosa!',
  '🌊 Flua com a vida!',
  '🔮 Seu futuro é brilhante!',
 
  // Crescimento e Aprendizado
  '📚 Cada dia é uma oportunidade de aprender!',
  '🧠 Seu cérebro é poderoso!',
  '🌱 Cresça todos os dias!',
  '🌿 Da semente vem a floresta!',
  '🎓 Você é sua melhor professora!',
  '📖 Escreva sua própria história!',
  '🔬 Experimente coisas novas!',
  '🧩 As peças se encaixarão!',
  '🎯 Foco e crescimento andam juntos!',
  '🌳 Sua raiz será profunda!',
  '💡 Ideias brilhantes nascem dentro de você!',
  '🔓 Abra as portas do conhecimento!',
  '🌐 O mundo é sua sala de aula!',
  '📝 Anote seus progressos!',
  '🚪 Cada porta leva a novas possibilidades!',
  '🎢 A jornada do crescimento é emocionante!',
  '🧗 Escale seu potencial!',
  '🎯 Mirar na excelência!',
  '🏃 Corra atrás de seu conhecimento!',
  '🎪 Circo da aprendizagem nunca fecha!',
 
  // Positividade e Esperança
  '🌞 A positividade atrai sucesso!',
  '🎉 Celebre cada pequena vitória!',
  '🎊 Você merece festejar!',
  '😊 Sorria, o melhor está por vir!',
  '🌅 O amanhã é promissor!',
  '🌈 Após a chuva, vem o arco-íris!',
  '☀️ Você é tão brilhante quanto o sol!',
  '🌟 Sua luz não pode ser apagada!',
  '💫 Estrelas também têm sombras, mas brilham!',
  '🎆 Seja fogos de artifício de alegria!',
  '🎇 Ilumine a escuridão!',
  '🕯️ Uma vela é melhor que amaldiçoar a escuridão!',
  '🔦 Seja a luz no caminho de alguém!',
  '💥 Sua presença é explosiva e positiva!',
  '🌺 Espalhe alegria!',
  '🦋 Transformação é linda!',
  '🌸 Floresça sempre!',
  '🌻 Gire em direção à luz!',
  '🌷 Delicadeza com força!',
  '🌼 Beleza natural em você!',
 
  // Foco e Determinação
  '🎯 Foco é o segredo do sucesso!',
  '🔍 Veja claramente seus objetivos!',
  '🧭 Sua bússola interna aponta para o sucesso!',
  '📍 Saiba exatamente onde quer chegar!',
  '🛣️ Siga a estrada do seu propósito!',
  '🚀 Decolagem para o sucesso agora!',
  '💨 Velocidade e determinação juntas!',
  '⚡ Energia máxima ativada!',
  '🔥 Fogo da determinação aceso!',
  '💪 Músculos da vontade contraídos!',
  '🏃 Corra em sua própria velocidade!',
  '🚴 Pedale em direção aos seus sonhos!',
  '🏊 Nade contra a corrente se necessário!',
  '🧗 Suba, mesmo que lentamente!',
  '⛰️ Montanhas foram feitas para serem escaladas!',
  '🛤️ Siga o caminho com confiança!',
  '🗺️ Você tem um mapa mental claro!',
  '🧲 Atração para o sucesso!',
  '🎪 Circo do sucesso começa aqui!',
  '🎭 O palco do sucesso é seu!',
 
  // Autoestima e Confiança
  '👑 Você é digna de respeito!',
  '💎 Você é uma joia rara!',
  '🦁 Tenha a confiança de uma leoa!',
  '🌟 Você brilla naturalmente!',
  '✨ Sua confiança é seu superpower!',
  '🔐 Segurança em si mesma é fundamental!',
  '🛡️ Proteja sua autoestima!',
  '🏰 Construa seu castelo de confiança!',
  '👸 Você é royalty!',
  '🤴 Seu valor é inquestionável!',
  '💪 Você é forte mentalmente!',
  '🧠 Sua mente é seu maior ativo!',
  '❤️ Ame-se incondicionalmente!',
  '💕 Você merece amor próprio!',
  '💖 Seu coração é valioso!',
  '💝 Você é um presente para si mesma!',
  '🌹 Sua beleza é interior!',
  '🦚 Pavoa não precisa de validação!',
  '🎨 Você é uma obra-prima!',
  '🖼️ Seu retrato é especial!',
 
  // Gratidão e Apreciação
  '🙏 Agradeça pelos pequenos momentos!',
  '🍂 Cada folha caída tem sua beleza!',
  '🌾 A colheita é resultado do trabalho!',
  '🎁 Cada dia é um presente!',
  '🎀 Desembrulhe as surpresas da vida!',
  '❤️ Gratidão abre corações!',
  '🌻 Apreciar é viver plenamente!',
  '🌺 Cada flor tem sua hora!',
  '🦋 Aprecie as transformações!',
  '🌈 Cores da vida precisam ser apreciadas!',
  '☀️ Aprecie a luz do dia!',
  '🌙 Aprecie o repouso da noite!',
  '⭐ Cada estrela merece atenção!',
  '🌟 Brilhe com gratidão!',
  '💫 Pequenas coisas, grande alegria!',
  '✨ Magia está nos detalhes!',
  '🎊 Celebre a vida!',
  '🎉 Festeje sua existência!',
  '🎈 Levante-se com esperança!',
  '🎀 Embrulhe seu dia em alegria!',
 
  // Relacionamentos e Conexão
  '🤝 As pessoas fazem a vida valer!',
  '💑 Ame e seja amada!',
  '👨‍👩‍👧‍👦 Família é tudo!',
  '👫 Conexões autênticas são ouro!',
  '🤗 Um abraço cura!',
  '😊 Um sorriso contagia!',
  '💬 Converse do coração!',
  '👂 Escute com empatia!',
  '❤️ Amor é o maior poder!',
  '💕 Relate-se genuinamente!',
  '💖 Mostrem amor sempre!',
  '💝 Pequenos gestos importam!',
  '🌹 Ofereça rosas de gentileza!',
  '🤲 Mãos abertas, coração aberto!',
  '🙌 Celebre os outros!',
  '👏 Aplauda o sucesso alheio!',
  '🎺 Anuncie a beleza dos outros!',
  '🎵 Cante louvores!',
  '🎶 Ritmo da amizade sincera!',
  '🎼 Harmonia nos relacionamentos!',
 
  // Saúde e Bem-estar
  '🏃 Movimento é medicina!',
  '🧘 Encontre paz interior!',
  '🥗 Nutra seu corpo!',
  '💧 Hidratação é essencial!',
  '🛌 Durma bem, acorde melhor!',
  '😴 O descanso alimenta a alma!',
  '🌬️ Respire fundo e relaxe!',
  '🧘‍♂️ Meditação traz clareza!',
  '🏋️ Fortaleça seu corpo!',
  '🤸 Seja ativa e viva!',
  '🚴 Movimente-se com alegria!',
  '⛹️ Jogue com energia!',
  '🏊 Nade em bem-estar!',
  '🧗 Escale sua saúde!',
  '🍎 Saúde começa na mesa!',
  '🥕 Alimento é combustível!',
  '🌽 Nutrir é amar!',
  '🥦 Verde é vida!',
  '🍊 Vitaminas e sorrisos!',
  '🍇 Pequenas frutas, grandes benefícios!',
 
  // Superação e Resiliência
  '🌊 As ondas passam!',
  '🏔️ Montanhas podem ser escaladas!',
  '❄️ Mesmo no frio, há calor!',
  '🌪️ Tempestades passam!',
  '⛈️ Após a chuva, sol!',
  '🔥 Do fogo surge a força!',
  '💨 Vento não te derruba!',
  '🌳 Árvores se dobram mas não quebram!',
  '🪨 Pedras são resilientes!',
  '🦾 Você é mais forte que pensa!',
  '🦾 Força vem da perseverança!',
  '🛡️ Defenda seus sonhos!',
  '⚔️ Lute pelos seus objetivos!',
  '🏹 Precisão na persistência!',
  '🎯 Alvo: superação!',
  '🚀 Decolagem em 3, 2, 1!',
  '🌟 Brilhe apesar dos obstáculos!',
  '✨ Mágica vem da persistência!',
  '💫 Você é invencível!',
  '⭐ Sua estrela não se apaga!',
 
  // Sonhos e Ambição
  '🌙 Sonhe bem!',
  '✨ Seus sonhos são válidos!',
  '🎆 Sonhos explodem em cores!',
  '🎇 Fogos de artifício de esperança!',
  '🌟 Sonhe em GRANDE!',
  '💫 Nenhum sonho é pequeno demais!',
  '🚀 Sonhe alto, voe fundo!',
  '🛸 Navegue pelo universo dos sonhos!',
  '🌌 Galáxia de possibilidades!',
  '🪐 Cada planeta é um novo sonho!',
  '☄️ Meteorito de ambição!',
  '🌠 Chuva de meteoros de sucesso!',
  '🌃 Vislumbre o horizonte!',
  '🌆 Cidade dos sonhos o aguarda!',
  '🏙️ Construa seu império!',
  '🏰 Seu castelo espera!',
  '👑 Use sua coroa de sonhos!',
  '💎 Pedras preciosas de ambição!',
  '🔮 O futuro pertence aos sonhadores!',
  '🎪 Circo mágico dos sonhos!',
 
  // Criatividade e Inovação
  '🎨 Sua criatividade não tem limites!',
  '🖌️ Pinte sua vida em cores vivas!',
  '🖍️ Desenhe seu futuro!',
  '✏️ Escreva sua épica!',
  '✒️ Tinta da inovação!',
  '📝 Página em branco: possibilidades infinitas!',
  '📖 Livro aberto da criatividade!',
  '📚 Biblioteca de ideias!',
  '💡 Luz criativa acesa!',
  '🔆 Brilho da imaginação!',
  '🌈 Arco-íris de possibilidades!',
  '🎭 Teatro da criatividade!',
  '🎪 Circo de ideias!',
  '🎨 Tela em branco esperando!',
  '🖼️ Sua obra-prima começa aqui!',
  '🎬 Filme do seu sucesso!',
  '🎥 Câmera, ação, criatividade!',
  '🎞️ Quadros de inovação!',
  '🎵 Música da engenhosidade!',
  '🎶 Melodia do sucesso!',
 
  // Diversidade de Motivação
  '🎊 Toda hora é hora de celebrar!',
  '🎉 Diversidade traz força!',
  '🌍 O mundo é seu playground!',
  '🌎 Seja global, pense local!',
  '🌏 Conecte com o planeta!',
  '🗺️ Sua jornada é única!',
  '🧭 Navegue com propósito!',
  '⛵ Vele para a vitória!',
  '🚢 Navio do sucesso zarpa!',
  '⚓ Ancorada em seus valores!',
  '🏊 Nade contra a maré!',
  '🏄 Surfe na vida!',
  '🚣 Remar para frente!',
  '🛶 Pequenos barcos também chegam!',
  '✈️ Voe alto!',
  '🚁 Elevação em vista!',
  '🚂 Viagem do sucesso começou!',
  '🚃 Trilhos do destino!',
  '🚄 Trem expresso do êxito!',
  '🚅 Alta velocidade para a glória!',
 
  // Mais Positividade e Energia
  '⚡ Energia sem limite!',
  '🔋 Bateria recarregada!',
  '🔌 Conectada ao sucesso!',
  '💡 Lâmpada de ideias!',
  '🕯️ Chama viva da determinação!',
  '🔥 Fogueira do sucesso!',
  '🌟 Brilho radiante!',
  '✨ Brilho mágico!',
  '💫 Cintilação de esperança!',
  '⭐ Estrela em ascensão!',
  '🌠 Trilha de sucesso!',
  '🌌 Universo de oportunidades!',
  '🪐 Planeta oportunidade!',
  '☄️ Impacto positivo!',
  '🌋 Vulcão de potencial!',
  '⛰️ Pico do sucesso!',
  '🏔️ Montanha conquistável!',
  '🗻 Cume em vista!',
  '🏕️ Base camp do triunfo!',
  '🏞️ Paisagem linda pela frente!',
 
  // Qualidades Pessoais
  '💪 Você é determinada!',
  '🧠 Você é inteligente!',
  '❤️ Você é bondosa!',
  '👁️ Você é perspicaz!',
  '👂 Você é empática!',
  '🙌 Você é generosa!',
  '👐 Você é acolhedora!',
  '💬 Você é eloquente!',
  '🤐 Você é discreta!',
  '👃 Você é intuitiva!',
  '🧭 Você é direcionada!',
  '🎯 Você é precisa!',
  '🔍 Você é observadora!',
  '🔎 Você é investigadora!',
  '📍 Você é focada!',
  '🗺️ Você é estratégica!',
  '📊 Você é analítica!',
  '📈 Você é progressiva!',
  '📉 Você aprende com quedas!',
  '💹 Seu valor cresce!',
 
  // Ação e Movimento
  '🏃 Comece agora!',
  '🚶 Cada passo conta!',
  '🧗 Suba sempre!',
  '🚴 Pedale com força!',
  '🏊 Nade fundo!',
  '⛹️ Jogue para ganhar!',
  '🤸 Seja flexível!',
  '🤾 Jogue como campeã!',
  '🤺 Espadachim da vida!',
  '🏹 Arqueira do sucesso!',
  '🎣 Pesque oportunidades!',
  '🥊 Lute com garra!',
  '🥋 Disciplina oriental!',
  '🏋️ Levante pesos maiores!',
  '🤼 Luta até a vitória!',
  '🏌️ Golpear certo!',
  '🏇 Galopada ao sucesso!',
  '🧗 Escalada ao topo!',
  '🚴 Pedal acelerado!',
  '🏃 Velocidade total!',
 
  // Inspiração Geral
  '🌟 Você é a estrela!',
  '✨ Magia em suas mãos!',
  '💫 Celestial e terrestre!',
  '⭐ Brilhe eternamente!',
  '🌠 Deixe um rastro!',
  '🌌 Infinito em você!',
  '🌃 Seu horizonte é vasto!',
  '🌆 Cidades ao seu comando!',
  '🌇 Pôr do sol de vitória!',
  '🌅 Amanhecer de possibilidades!',
  '🌄 Montanha ao amanhecer!',
  '🌉 Ponte para o sucesso!',
  '🌁 Nevoeiro do mistério!',
  '🎑 Noite de realizações!',
  '🌀 Espiral de crescimento!',
  '🌈 Promessa após a chuva!',
  '🌤️ Tempo melhorando!',
  '⛅ Céu misturado, mas esperançoso!',
  '🌥️ Nuvens passam!',
  '☁️ Macieza flutuante!',
 
  // Força Interior
  '🔐 Sua força é interna!',
  '🔓 Abra seu coração!',
  '🔒 Segure seus valores!',
  '🗝️ Chave do sucesso!',
  '🔑 Desbloqueie potencial!',
  '⚔️ Espada da determinação!',
  '🛡️ Escudo do caráter!',
  '🏹 Flecha da precisão!',
  '🎯 Centro do sucesso!',
  '💣 Explosão de criatividade!',
  '💥 Impacto positivo!',
  '🔥 Fogo interior!',
  '❄️ Calma em tempos frios!',
  '💧 Fluidez na adaptação!',
  '🌪️ Tempestade de energia!',
  '⚡ Raio de potencial!',
  '☄️ Meteoro de sucesso!',
  '🌊 Onda de força!',
  '🗻 Montanha de estabilidade!',
  '🌋 Vulcão de poder!',
];
